name: epp_app
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter
  
  path_provider: ^2.1.2
  cupertino_icons: ^1.0.8
  supabase_flutter: ^2.8.0
  crypto: ^3.0.3
  file_picker: ^8.0.0
  pdf: ^3.11.3
  printing: ^5.13.0
  intl: ^0.19.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  uuid: ^4.4.2
  image_picker: ^1.0.0
  connectivity_plus: ^6.0.0
  signature: ^5.4.0
  geolocator: ^13.0.0
  device_info_plus: ^10.1.0
  camera: ^0.10.5+9
  google_mlkit_face_detection: ^0.11.0
  flutter_image_compress: ^2.3.0


#dependencies:
#  hive: ^2.2.3
#  hive_flutter: ^1.1.0
#  uuid: ^4.4.2


dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0


flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "app_icon.png"
  min_sdk_android: 21
  adaptive_icon_background: "#0D2148"
  adaptive_icon_foreground: "app_icon.png"
